### ISSUE TITLE
pfr::ops doesn't support unions in PODs

### ISSUE THREAD

**Issue by anthonygclark** [apolukhin/magic_get#22]
First off, I love this library. I find myself writing a lot of binary protocols that support unions. One thing I do to  test out my binary parsers/generators, is just sending the instance to `operator<<` and not having to write a 100+ line function myself, I love this (ehm, Rust has this as well).

Any ideas on how you could support unions? Maybe just convert to `std::tuple<>` and print that? I've gotten `boost::hana` to play nice sometimes but nothing notable. I think if you support unions, lots of C code or legacy C++ could be brought to a new light by just automatically having `pfr::ops` work.

Thanks!

**Comment by apolukhin** [comment]
I've added some tests for unions  in e7abff6 and they seem to work.

Could you please provide some usage examples that do not work?

**Comment by apolukhin** [comment]
Unfortunately I have no idea to how to do it right.

When we are working with

**Comment by anthonygclark** [comment]
@apolukhin Yea, I guess having anything nested causes issues. That doesn't seem like a defect with your library. Though making the claim that you can generate an `operator<<(ostream &, ...)` for all PODs would then be untrue has PODs can be nested. ie - `std::is_pod<some_person>::value == true`. I'm not even sure this is possible.

I really appreciate the help @apolukhin.

**Comment by apolukhin** [comment]
I'll do some experiments and will try to come up with something reasonable. Probably you're right and there's some way to reflect unions safe and right.

**Comment by cbeck88** [comment]
@anthonygclark I think you might want to look into using a variant type like `boost::variant` instead of `union`, and then it would support streaming operator directly and correctly

**Comment by anthonygclark** [comment]
@cbeck88

The issue is legacy. If I were writing all new code, then all would be well. But I’m trying to find a nice way to display large (sometimes 50+) structures that are spewed over a wire. For this, lots of hardware uses packed structures, unions,  and unaligned arrays. I’m thinking a tool to spit out an unsafe printf call from a structure definition is probably better. 

Btw, an std::variant and union are not really the same physically so variant doesn’t apply.

**Comment by cbeck88** [comment]
> For this, lots of hardware uses packed structures, unions,  and unaligned arrays.

`magic_get` works by using some template trickery to extract, given a struct, the types (and order) of the members, then it uses internal logic to deduce the offsets of the members based on that information. It used to work by simply reinterpret_cast'ing your struct as an "equivalent" tuple, it now does something only slightly different that is standards compliant.

If you have packed structs, i.e. with `__attribute__((packed))` I'd say it has a snowball's chance in hell of working anyways, because all the offsets are going to be wrong. There's no way for a template to determine that your struct is packed. Actually I thought we had a `static_assert` that the size we expect based on the layout that we compute is the same as the true size of the struct, which would handle the "packed" case.

I guess we could try to fix it by checking if your struct has the "packed" size or the "unpacked" size, and then "deduce" what the layout is that way. Given that `__attribute__((packed))` is kind of squirrelly and implementation defined anyways, and this could make it harder to detect corruption, I wouldn't think most uses would want that to be on by default anyways.
